# Generated by Django 2.2.10 on 2020-02-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('hitpoints', models.IntegerField()),
            ],
        ),
    ]
