# Generated by Django 2.2.10 on 2020-02-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20200228_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='poke_id',
            field=models.IntegerField(default=1, verbose_name='PokeAPI ID'),
            preserve_default=False,
        ),
    ]
