# Generated by Django 2.2.10 on 2020-03-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemon_poke_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='hitpoints',
            new_name='hp',
        ),
    ]
