# Generated by Django 2.2.11 on 2020-03-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20200302_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='img_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
