# Generated by Django 2.2.10 on 2020-02-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='creater',
            new_name='creator',
        ),
    ]
