# Generated by Django 2.2.10 on 2020-03-03 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battles', '0004_battleteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
