# Generated by Django 2.2.10 on 2020-03-05 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0006_auto_20200303_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_battles', to=settings.AUTH_USER_MODEL),
        ),
    ]
