# Generated by Django 2.2.10 on 2020-03-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0009_battle_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
