# Generated by Django 2.2.10 on 2020-03-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0010_auto_20200311_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('SETTLED', 'SETTLED')], default='ONGOING', max_length=20),
        ),
    ]
