# Generated by Django 2.2.10 on 2020-03-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0011_auto_20200316_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'ONGOING'), ('SETTLED', 'SETTLED')], default='ONGOING', max_length=20, null=True),
        ),
    ]
